### ISSUE TITLE
How woud I implement Skill Animations?

### ISSUE THREAD

**Issue by Fallen-Entertainment** [insthync/UnityMultiplayerARPG_InvectorCharacterModel#3]
I love this addon, but It leaves me a little short on some animations and im not sure how to add them. Any insight you could provide would be appreciated.

**Comment by Safewaygames** [comment]
Yea this is great but missing skill animations and a few other things. any Insight on how we could add it ourself would be a great help.

**Comment by insthync** [comment]
Just add skill states to animator controller, and implement play skill animation functions, I won't do it, I already implement all of this without anyone paid, and I don't want to do anything without being paid anymore.

I actually just want to do it as an example of how to implement a custom character model, but it seems like it has no one can do it except me. It already has many character models, but it will never be enough.
